/* js/changelog-head.js — GENERATED by tools/changelog-normalize.js. DO NOT EDIT.
   The boot-path slice of js/changelog.js (AUD-08): just enough for the footer stamp,
   the version label and the What's-new unseen dot, so the ~680KB of full history is
   fetched lazily (Studio.loadChangelog) the first time someone opens the feed.
   Regenerated from js/changelog.js on every normalize run — never hand-edit. */
window.STUDIO_LATEST_VERSION = 879;
window.STUDIO_LATEST = {"v":879,"title":"The builder calls its own left panel Data, and the button that opens it works on a phone","kind":"fix","ts":"2026-08-08T03:46:44.000Z"};
window.STUDIO_BUILD = "__BUILD_TS__";
