/* js/changelog-head.js — GENERATED by tools/changelog-normalize.js. DO NOT EDIT.
   The boot-path slice of js/changelog.js (AUD-08): just enough for the footer stamp,
   the version label and the What's-new unseen dot, so the ~680KB of full history is
   fetched lazily (Studio.loadChangelog) the first time someone opens the feed.
   Regenerated from js/changelog.js on every normalize run — never hand-edit. */
window.STUDIO_LATEST_VERSION = 886;
window.STUDIO_LATEST = {"v":886,"title":"Signing in no longer spends your renewal token twice","kind":"fix","ts":"2026-08-08T10:12:10.000Z"};
window.STUDIO_BUILD = "__BUILD_TS__";
